### ISSUE TITLE
Are you a teacher?

### ISSUE THREAD

**Issue by Leichesters** [Bnyro/chatoyer.de#1]
I once had a teacher called Chatoyer. Are you her?

**Comment by Bnyro** [comment]
No, neither my name is Chatoyer nor am I a teacher.

**Comment by Leichesters** [comment]
Why this name then?

**Comment by Bnyro** [comment]
https://dictionary.cambridge.org/dictionary/french-english/chatoyer

**Comment by Leichesters** [comment]
That's funny because she was also from France

**Comment by kamlendras** [comment]
make reflections that change color
